name: Release
permissions:
  contents: write

defaults:
  run:
    shell: sh

on:
  release:
    types: [published]

env:
  BUILD_TYPE: Release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create build environment
        run : cmake -E make_directory build

      - name: CMake Configure
        working-directory: build/
        run : >
          cmake $GITHUB_WORKSPACE -D CMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
          -D MQLQD_BUILD_TESTS=OFF -D MQLQD_COVERAGE_ENABLE=OFF

      - name: Package source code
        working-directory: build/
        run : cmake --build . --target mqlqd_package -j $(getconf _NPROCESSORS_ONLN)

      - name: Add packaged source code to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/mqlqd-src.zip
          tag : ${{ github.ref }}

